# Generated by Django 3.2.3 on 2021-06-01 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='company_images'),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='logo',
            field=models.ImageField(upload_to='speciality_images'),
        ),
    ]
