# Generated by Django 3.2.3 on 2021-06-07 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_auto_20210603_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vacancy',
            name='speciality',
        ),
        migrations.AddField(
            model_name='vacancy',
            name='speciality',
            field=models.ForeignKey(default='backend',
                                    on_delete=django.db.models.deletion.CASCADE,
                                    related_name='vacancies',
                                    to='jobs.speciality'),
        ),
    ]
